"""The Account table added created_at and updated_at fields

Revision ID: 69f1fb6a7888
Revises: aaaab18ab2bd
Create Date: 2025-09-13 18:49:13.669908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69f1fb6a7888'
down_revision: Union[str, Sequence[str], None] = 'aaaab18ab2bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('accounts', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'updated_at')
    op.drop_column('accounts', 'created_at')
    # ### end Alembic commands ###
