"""Added role on table Account

Revision ID: 92cf435449d0
Revises: 69f1fb6a7888
Create Date: 2025-09-14 19:28:29.793173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92cf435449d0'
down_revision: Union[str, Sequence[str], None] = '69f1fb6a7888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('role', sa.Enum('ADMIN', 'USER', 'MANAGER', name='role'), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'role')
    # ### end Alembic commands ###
